### PR TITLE
v2.2.0/transaction/call and .../create

### PR DESCRIPTION
**Pull request by witoldsz**

### CODE REVIEW

**Comment by honeycrypto** [comment]
@witoldsz it's a good moment to merge this and migrate testnet api to "Tesnet 2": 
https://github.com/semuxproject/semux-core/releases

**Comment by witoldsz** [comment]
Unfortunately, I have to reject this pull request. These two endpoints (…/call and …/create) are preparing transactions signed by the keys of the host. That would give users of the gateway (indirect) access to the private key… or would rather be useless as I don't even publish the account address of that Semux host.

See the description of these endpoints, the _from_ field:

> Sender’s address. The address must exist in the wallet.data of this Semux node.

**Comment by witoldsz** [comment]
P.S.
One can still use the API gateway to create and call EVM contracts, but the raw transaction must be created and signed elsewhere, just like other actions, e.g. transfer funds or voting.

**Comment by witoldsz** [comment]
P.P.S
The https://api.testnet.semux.online is migrated to "Testnet 2" already :)

**Comment by orogvany** [comment]
Please add transactionresult and update create-raw-transaction to support creating unsigned create/call. 

Right now it only has 

Transaction typeAvailable values : TRANSFER, DELEGATE, VOTE, UNVOTE
--

**Comment by orogvany** [comment]
Ah. That's semux bug. Will update. Though you will want transaction-result and new call-local. Neither are write operations

**Comment by witoldsz** [comment]
@orogvany the `/transaction-result` in #3. There is no `call-local` yet in the API though `¯\_('o')_/¯`

**Comment by orogvany** [comment]
Thanks.  Call-local pr up. Just need to finish writing unit tests

**Pull request closed without merging**
